### ISSUE TITLE
Increase space between phone number and email details in row header.

### ISSUE THREAD

**Issue by shivhek25** [lugnitdgp/Modern-English-School-practice#2]

**Comment by mahak5** [comment]
I would like to contribute to the fixing of this issue.

**Comment by shivhek25** [comment]
Okay. I'm sure you have cloned the repo already and are familiar with Bootstrap.

**Comment by shivhek25** [comment]
Any progress ?

**Comment by mahak5** [comment]
Ya,done with the work.Creating a pull request in sometime

**Comment by shivhek25** [comment]
The previous PR didn't solve the issue but you fixed it yourself later. Well done !
